### PR TITLE
Adding buildQuery helper with array of conditions

### PR DESCRIPTION
**Pull request by mouadziani**

### CODE REVIEW

**Comment by nouraellm** [comment]
take a look at "where 1" tho

**Comment by AXeL-dev** [comment]
@nouraellm `where 1` is only used to avoid having an `AND` exactly after the where like: `select * from table where AND id = 1` because this will surely throw an SQL error, so even if the where condition looks like `where 1 AND id = 1` it should work fine.

**Comment by mouadziani** [comment]
@nouraellm Yep, that's exactly what I mean,

**Comment by nouraellm** [comment]
@MouadZIANI @AXeL-dev  I'll check that later

**Comment by mouadziani** [comment]
@nouraellm I forgot to remind u o this https://www.youtube.com/watch?v=papuvlVeZg8

**Pull request merged**
